name: PyPy Windows Benchmark
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 'pypy-3.10'
      - name: Run Benchmark
        run: python memoryview.py
